services:
  db:
    image: postgres:17
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5435:5432"
    volumes:
      - dashmin-pg-data:/var/lib/postgresql/data
    networks:
      - dashmin-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  dashmin-pg-data:
    name: dashmin-pg-data

networks:
  dashmin-network:
    driver: bridge
